version: '3.8'
services:
  db:
    image: postgres:15
    container_name: gym_postgres_db
    restart: always
    environment:
      POSTGRES_USER: gymuser
      POSTGRES_PASSWORD: gympassword
      POSTGRES_DB: gymdatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: